### ISSUE TITLE
没找到 wiki 的编辑和新建按纽

### ISSUE THREAD

**Issue by suredream** [opengeos/Awesome-GEE#3]

**Comment by giswqs** [comment]
I just invited you as a collaborator for this repo. You should be able to edit the wiki once you accept the invite.

**Comment by suredream** [comment]
Don't know why but it still didn't work after I received the invitation.

**Comment by giswqs** [comment]
The status is pending. You need to accept the invite.

![](https://i.imgur.com/kj2I5g7.png)
